language: c

compiler:
    - gcc
    - clang

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install codecov; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install cunit; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install --HEAD valgrind; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y -qq libcunit1 libcunit1-dev lcov valgrind; fi

install:

script:
    - mkdir build
    - cd build
    - cmake .. -DDISABLE_VALGRIND:BOOL=false
    - make
    - make test

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then codecov; fi
